import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css'
import "./globals.scss";
import BootstrapClient from './components/BootstrapClient';
import Script from "next/script"
import { PiHouse } from "react-icons/pi";
import { MdOutlinePhone } from "react-icons/md";
import { LuBuilding2 } from "react-icons/lu";
import { FiPackage } from "react-icons/fi";
import { SlSocialFacebook } from "react-icons/sl";
import { CiTwitter } from "react-icons/ci";
import { FaEnvelope } from "react-icons/fa";
import { FaLinkedinIn } from "react-icons/fa";
import { FaRegEnvelope } from "react-icons/fa6";
import { FaRegClock } from "react-icons/fa6";
import { TbWorld } from "react-icons/tb";
import { IoLocationOutline } from "react-icons/io5";
import { FaChevronRight } from "react-icons/fa";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Terzigroup",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Inter ve Poppins fontlarını Google Fonts'tan ekliyoruz */}
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&family=Poppins:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
        <nav className="terzi-navbar navbar navbar-expand-lg">
          <div className="contact-top">
            <div className="container">
              <a className="contact-link">
                <MdOutlinePhone className="icon"/> 0850 123 45 67
              </a>
              <a className="contact-link">
                <FaRegEnvelope className="icon"/> destek@terziflow.com
              </a>
              <a className="contact-link">
                <FaRegClock className="icon"/> Pzt-Cum 08:00-18:00
              </a>
            </div>
          </div>
          <div className="container">
            <a className="navbar-brand" href="#">
              <img className="bonero1" src="/main/logo_text.svg"></img>
            </a>
            <button
              className="navbar-toggler"
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span className="navbar-toggler-icon" />
            </button>
            <div className="collapse navbar-collapse" id="navbarSupportedContent">
              <ul className="navbar-nav mx-auto mb-lg-0">
                <li className="nav-item">
                  <a className="nav-link active" aria-current="page" href="/">
                    <PiHouse className="link-icon"/> Ana Sayfa
                  </a>
                </li>
                <li className="nav-item">
                  <a className="nav-link" href="/kurumsal">
                    <LuBuilding2 className="link-icon"/> Kurumsal
                  </a>
                </li>
                <li className="nav-item">
                  <a className="nav-link" href="/tedarik">
                    <FiPackage className="link-icon"/> Tedarik
                  </a>
                </li>
                <li className="nav-item">
                  <a className="nav-link" href="/iletisim">
                    <MdOutlinePhone className="link-icon"/> İletişim
                  </a>
                </li>
              </ul>
              <form className="d-flex" role="search">
                <button className="btn contact-button" type="submit">
                  İletişime Geç
                </button>
              </form>
            </div>
          </div>
        </nav>      
        {children}
        <footer className="footer">
          <div className="container">
            <div className="footer-container">
              <div className="row">
                <div className="col-lg-3 col-md-6">
                  <div className="footer-section about">
                    <h2 className="logo"><img src="/main/footer.svg"></img></h2>
                    <p>
                      Uluslararası alanda faaliyet gösteren toptan ticaret şirketi olarak, kalite ve güvenilirlik odaklı hizmet anlayışımızla sektörde öncüyüz.
                    </p>
                    <div className="d-flex gap-3 my-4">
                      <a href="https://facebook.com" target="_blank" rel="noopener noreferrer" className="social-icon">
                        <div className="social-icon-inner"><FaEnvelope /></div>         
                      </a>
                      <a href="https://facebook.com" target="_blank" rel="noopener noreferrer" className="social-icon">
                        <div className="social-icon-inner"><MdOutlinePhone /></div>         
                      </a>
                      <a href="https://facebook.com" target="_blank" rel="noopener noreferrer" className="social-icon">
                        <div className="social-icon-inner"><TbWorld /></div>         
                      </a>
                      <a href="https://facebook.com" target="_blank" rel="noopener noreferrer" className="social-icon">
                        <div className="social-icon-inner"><IoLocationOutline /></div>         
                      </a>
                    </div>
                  </div>
                </div>
                
                <div className="col-lg-3 col-md-6">
                  <div className="footer-section links">
                    <h3 className="mb-4">Hizmetlerimiz</h3>
                    <ul>
                      <li><a href="#"><FaChevronRight className="footer-icon"/> Gıda Ürünleri Toptan Satış</a></li>
                      <li><a href="#"><FaChevronRight className="footer-icon"/> İçecek Dağıtımı</a></li>
                      <li><a href="#"><FaChevronRight className="footer-icon"/> Ambalaj Malzemeleri</a></li>
                      <li><a href="#"><FaChevronRight className="footer-icon"/> Hijyen Ürünleri</a></li>
                      <li><a href="#"><FaChevronRight className="footer-icon"/> Soğuk Zincir Lojistik</a></li>
                      <li><a href="#"><FaChevronRight className="footer-icon"/> Özel Ürün Tedariki</a></li>
                      <li><a href="#"><FaChevronRight className="footer-icon"/> Profesyonel Danışmanlık</a></li>
                      <li><a href="#"><FaChevronRight className="footer-icon"/> 24/7 Müşteri Desteği</a></li>
                    </ul>
                  </div>
                </div>
                
                <div className="col-lg-3 col-md-6">
                  <div className="footer-section links">
                    <h3 className="mb-4">Hizmet Bölgeleri</h3>
                    <ul>
                      <li><a href="#"><IoLocationOutline className="footer-icon"/> Stuttgart & Umgebung</a></li>
                      <li><a href="#"><IoLocationOutline className="footer-icon"/> Baden-Württemberg</a></li>
                      <li><a href="#"><IoLocationOutline className="footer-icon"/> Bayern</a></li>
                      <li><a href="#"><IoLocationOutline className="footer-icon"/> Hessen</a></li>
                      <li><a href="#"><IoLocationOutline className="footer-icon"/> Rheinland-Pfalz</a></li>
                      <li><a href="#"><IoLocationOutline className="footer-icon"/> Nordrhein-Westfalen</a></li>
                      <li><a href="#"><IoLocationOutline className="footer-icon"/> Gesamte Deutschland</a></li>
                      <li><a href="#"><IoLocationOutline className="footer-icon"/> Europa (auf Anfrage)</a></li>
                    </ul>
                  </div>
                </div>
                
                <div className="col-lg-3 col-md-6">
                  <div className="footer-section">
                    <h3 className="mb-4">İletişim</h3>
                    <h6><IoLocationOutline className="footer-icon"/> Hauptsitz</h6>
                    <p className="m-0">
                      Musterstraße 123, 70173 Stuttgart,
                    </p>
                    <p>
                      Deutschland
                    </p>
                    <h6><MdOutlinePhone className="footer-icon"/> Telefon</h6>
                    <p>
                      +49 (0) 711 234 567
                    </p>
                    <h6><FaEnvelope className="footer-icon"/> E-Mail</h6>
                    <p>
                      info@terzigroup.com
                    </p>
                    <h6><FaRegClock className="footer-icon"/> Çalışma Saatleri</h6>
                    <p className="m-0">
                      Pazartesi - Cuma: 07:00 - 18:00
                    </p>
                    <p className="m-0">
                      Cumartesi: 08:00 - 14:00
                    </p>
                    <p>
                      Pazar: Kapalı
                    </p>
                  </div>
                </div>
              </div>          
            </div>
            <div className="footer-middle subscribe text-center">
              <div className="row">
                <form>
                  <h2>Newsletter'ımıza Katılın!</h2>
                  <p>Özel fırsatlar, yeni ürünler ve sektör haberlerinden ilk siz haberdar olun.</p>
                  <input className="me-2" type="email" placeholder="E-mail adresiniz" required />
                  <button className="ms-2" type="submit">Abone ol</button>
                </form>
              </div>
            </div>
            <div className="footer-bottom">
              <div className="row">
                <div className="col-md-3 d-flex align-items-center justify-content-center">
                  <p className=" mb-0">© 2025 Terzi Group. Tüm hakları saklıdır.</p>
                </div>
                <div className="col-md-6 d-flex align-items-center justify-content-center">
                  <a className="footer-bottom-link me-3" href="#">Datenschulz</a>
                  <a className="footer-bottom-link me-3" href="#">Impressum</a>
                  <a className="footer-bottom-link me-3" href="#">AGB</a>
                  <a className="footer-bottom-link me-3" href="#">Cookie-Richtlinie</a>
                </div>
                <div className="col-md-3 d-flex align-items-center justify-content-center">
                  <p className=" mb-0">Made with ❤️ in Stuttgart</p>
                </div>
              </div>
            </div>
          </div>
        </footer>
        <BootstrapClient/>
        </body>
    </html>
  );
}
